bluesea_node:
  ros__parameters:
  #ROS2#
    frame_id: "laser"
    scan_topic: "scan"
    cloud_topic: "cloud"
  #DATA#
    dev_id: -1
    raw_bytes: 3
    output_360: true
    output_scan: true
    output_cloud2: false
    with_angle_filter: false
    min_angle: -3.1415926
    max_angle: 3.1415926
    # with_angle_filter: true
    # mask1: "0.777,0.993"
    # mask2: "2.149,2.364"
    # mask3: "-2.364,-2.149"
    # mask4: "-0.993,-0.777"
    hard_resample: false
    soft_resample: false
    with_checksum: true
    reversed: false
    min_dist: 0.3
    max_dist: 50.0
    error_circle: 3
    error_scale: 0.9
#CONNECT#
    type: "uart"
    port: "/dev/cp210x_lidar"
    baud_rate: 921600
  #GET#
    uuid:  -1
  #SET#
    resample_res: -1.0
    with_confidence: -1
    with_smooth: -1
    with_deshadow: 10
    alarm_msg: -1
    rpm: -1
